name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - 'mona/octocat'
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world"
