name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "step 1"
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "step build"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "step test"
